  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=movies
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    web:
      build: .
      environment:
        - DJANGO_SETTINGS_MODULE=project.docker
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      depends_on:
        - db

    test:
      build: .
      command: sh -c "pip install -r dev.txt 
        && python manage.py test"
