# Generated by Django 3.1 on 2020-09-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50, verbose_name='source')),
                ('value', models.CharField(max_length=50, verbose_name='value')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='year')),
                ('rated', models.CharField(default='N/A', max_length=50, verbose_name='rated')),
                ('released', models.DateField(null=True, verbose_name='released')),
                ('runtime', models.CharField(default='N/A', max_length=50, verbose_name='runtime')),
                ('genre', models.CharField(default='N/A', max_length=50, verbose_name='genre')),
                ('director', models.CharField(default='N/A', max_length=50, verbose_name='director')),
                ('writer', models.CharField(default='N/A', max_length=255, verbose_name='writer')),
                ('actors', models.CharField(default='N/A', max_length=255, verbose_name='actors')),
                ('plot', models.CharField(default='N/A', max_length=255, verbose_name='plot')),
                ('language', models.CharField(default='N/A', max_length=50, verbose_name='language')),
                ('country', models.CharField(default='N/A', max_length=50, verbose_name='country')),
                ('awards', models.CharField(default='N/A', max_length=50, verbose_name='awards')),
                ('poster', models.CharField(default='N/A', max_length=255, verbose_name='poster')),
                ('metascore', models.CharField(default='N/A', max_length=50, verbose_name='metascore')),
                ('imdb_rating', models.CharField(default='N/A', max_length=50, verbose_name='imdb_rating')),
                ('imdb_votes', models.CharField(default='N/A', max_length=50, verbose_name='imdb_votes')),
                ('imdb_id', models.CharField(default='N/A', max_length=50, verbose_name='imdb_id')),
                ('type', models.CharField(default='N/A', max_length=50, verbose_name='type')),
                ('dvd', models.DateField(null=True, verbose_name='dvd')),
                ('boxoffice', models.CharField(default='N/A', max_length=50, verbose_name='boxoffice')),
                ('production', models.CharField(default='N/A', max_length=50, verbose_name='production')),
                ('website', models.CharField(default='N/A', max_length=50, verbose_name='website')),
                ('ratings', models.ManyToManyField(default=[], to='movies.Rating')),
            ],
        ),
    ]
