# Generated by Django 3.1 on 2020-08-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='released',
            field=models.DateField(null=True, verbose_name='released'),
        ),
    ]
