# Generated by Django 3.1 on 2020-09-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200826_2055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
